#!/usr/bin/env bash
# Regenerate llms-full.txt: the README and every document of docs/rdna3/ concatenated, for LLMs that read one file.
# Run from anywhere after editing the docs (the release checklist does it). Optional argument: another output file.
set -euo pipefail
out="$(realpath -m "${1:-$(dirname "${BASH_SOURCE[0]}")/../../llms-full.txt}")"
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
docs=(README.md docs/rdna3/getting-started.md docs/rdna3/profiles.md docs/rdna3/options.md docs/rdna3/benchmarks.md
      docs/rdna3/how-it-works.md docs/rdna3/decisions.md docs/rdna3/journey.md docs/rdna3/limits.md
      docs/rdna3/troubleshooting.md docs/rdna3/testing.md docs/rdna3/maintaining.md docs/rdna3/changes-from-upstream.md
      docs/rdna3/credits.md)
{
  echo "# freetoken-rdna3: all documentation in one file"
  echo
  echo "Generated by rdna3/tools/make-llms-full.sh from the files below (each starts with a \"file:\" comment); edit"
  echo "those, not this one."
  for f in "${docs[@]}"; do printf '\n\n---\n\n<!-- file: %s -->\n\n' "$f"; cat "$f"; done
} > "$out"
echo "$(basename "$out"): $(wc -c < "$out") bytes from ${#docs[@]} files"
